[package]
name = "string-similarity"
version = "0.1.0"
authors = ["Evan Richter <evanjrichter@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
strsim = "0.10"
colored = "2.0"
argh = "0.1"
